# fish completion for anvil

complete -c anvil -s h -l help -d 'Show command help'
complete -c anvil -s V -l version -d 'Show version'
complete -c anvil -s c -l config -r -F -d 'Use an alternate config file'
complete -c anvil -s d -l working-directory -r -a '(__fish_complete_directories)' -d 'Start in a directory'
complete -c anvil -s e -l execute -r -a '(__fish_complete_command)' -d 'Run a command instead of the configured shell'
complete -c anvil -l mode -r -a 'block vte' -d 'Override the terminal backend'
complete -c anvil -l no-restore -d 'Start a fresh persistable workspace'
complete -c anvil -l safe-mode -d 'Use isolated VTE defaults without persistence'
complete -c anvil -l doctor -d 'Run headless environment diagnostics'
complete -c anvil -l json -d 'Format diagnostics as JSON'
complete -c anvil -l check-config -F -d 'Validate configuration'
complete -c anvil -l restore-config-backup -d 'Restore the newest valid config backup'
complete -c anvil -l config-path -d 'Print the effective config path'
complete -c anvil -l init-config -d 'Create a documented config if absent'
complete -c anvil -l print-default-config -d 'Print the bundled example config'
complete -c anvil -l shell-integration -r -a 'bash zsh fish pwsh' -d 'Print shell integration'
complete -c anvil -l generate-completion -r -a 'bash zsh fish pwsh' -d 'Print command completion'
complete -c anvil -l completion -r -a 'bash zsh fish pwsh' -d 'Alias for --generate-completion'
