//! Top-level Relm4 application messages.
//!
//! Keeping the event vocabulary separate from the component implementation
//! makes the update loop easier to navigate without changing Relm4 ownership.

use crate::keybindings::Action;

#[derive(Debug, Clone)]
pub(crate) enum AppMsg {
    NewTab,
    CloseTab(u64),
    ForceCloseTab(u64),
    ForceClosePane(u64),
    ForceCloseMarked(Vec<u64>),
    SelectTab(u64),
    NextTab,
    PrevTab,
    ToggleSidebar,
    Quit,
    ForceQuit,
    Toast(String),
    CopyOutputOnly,
    Action(Action),
    /// Result of the background "is a newer rsh published?" check. Boxed so one
    /// rare message does not widen every other variant.
    RshUpdateChecked(Box<jterm_core::rsh_install::Status>),
    ReloadConfig,
    PaneLaunchFailed(u64, String),
    PaneExited(u64, u64, i32),
    PaneCwdChanged(u64, u64, String, bool),
    PaneRemoteSessionId(u64, String),
    RemoteReconnectTick(u64, u64),
    RemoteReconnectNow(u64, u32),
    PaneFocused(u64, u64),
    /// A pane header was dropped onto another pane: exchange their positions
    /// in the split tree.
    SwapPanes {
        dragged: u64,
        target: u64,
    },
    /// Periodic refresh of the split panes' status headers (cwd and the
    /// running command are polled, not pushed).
    RefreshPaneHeaders,
    TitleChanged(u64, String),
    Bell(u64),
    Activity(u64),
    SettingsTheme(usize),
    SettingsFontDesc(String),
    SettingsFontScale(f64),
    SettingsOpacity(f64),
    SettingsScrollback(u32),
    SettingsTerminalMode(usize),
    SettingsBlockCompact(bool),
    SettingsCommandHistory(bool),
    SettingsAiEnabled(bool),
    SettingsAgentEnabled(bool),
    SettingsAiProvider(usize),
    SettingsAiModel(String),
    SettingsAiBaseUrl(String),
    SettingsAiKeyFile(String),
    SettingsAiMaxTokens(u32),
    SettingsAiRedactSecrets(bool),
    SettingsAgentMaxTurns(u32),
    SettingsNotifications(bool),
    SettingsRemoteClipboard(bool),
    SearchChanged(String),
    SearchNext,
    SearchPrev,
    SearchClose,
    SetTabWidth(u32),
    RenameTab(u64, String),
    ReorderTab(u64, usize),
    TabRowAction(u64, crate::tab_strip::TabAction),
    SetTabFilter(String),
    FileTreeActivateFile(String),
    OpenNotebook(std::path::PathBuf),
    OpenAgent,
    AgentSend(String),
    AgentContinue,
    AgentNewTask,
    AgentClearContext,
    AgentApprove(usize),
    AgentReject(usize),
    AgentEditAndApprove(usize, String),
    AgentEditRequested(usize, String),
    AgentLlmReply(Result<String, String>),
    AgentBlockFinished {
        tab_id: u64,
        pane_id: u64,
        command: String,
        exit_code: i32,
        output_sample: String,
    },
    AgentClose,
    FileTreeGotoCwd,
    FileTreeGoUp,
    SetSidebarView(crate::config::SidebarView),
    PaletteTypeCommand(String),
    PaletteAskAi(String),
    PaletteReviewAiCommand {
        pane_id: u64,
        command: String,
    },
    PaletteInsertAiCommand {
        pane_id: u64,
        command: String,
    },
    OpenAiPanel,
    AskAiAboutBlock(crate::ai::BlockContext),
    PaletteRunWorkflow(std::path::PathBuf),
    Ignore,
}
